INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) values (1, 'RAKESH', 'BASANI');
INSERT INTO PRODUCT (ID, TYPE, NAME, INTEREST_RATE) values (1, 'SAVINGS', 'Orange Savings Account', 3.5);
INSERT INTO PRODUCT (ID, TYPE, NAME, INTEREST_RATE) values (2, 'SAVINGS', 'Savings Deposit', 4.1);
INSERT INTO PRODUCT (ID, TYPE, NAME, INTEREST_RATE) values (3, 'SAVINGS', 'Bonus Interest Account', null);
INSERT INTO PRODUCT (ID, TYPE, NAME, INTEREST_RATE) values (4, 'MORTGAGE', 'Interest only', 5.0);
INSERT INTO CUSTOMER_PRODUCT (CUSTOMER_ID, PRODUCT_ID, AMOUNT) values (1, 1, 1000);
INSERT INTO CUSTOMER_PRODUCT (CUSTOMER_ID, PRODUCT_ID, AMOUNT) values (1, 2, 2000);
INSERT INTO CUSTOMER_PRODUCT (CUSTOMER_ID, PRODUCT_ID, AMOUNT) values (1, 3, null);
INSERT INTO CUSTOMER_PRODUCT (CUSTOMER_ID, PRODUCT_ID, AMOUNT) values (1, 4, 3000);